version: '3.7'

x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./scss:/app/scss
    - ./webpack.config.js:/app/webpack.config.js
    - ./babel.config.js:/app/babel.config.js

services:
  compile:
    build: .
    image: libcal-assets
    command: yarn build:prod
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    # <<: *default-volumes
  
  watch:
    build: .
    image: libcal-assets
    command: yarn build:dev:watch
    <<: *default-volumes

  dev:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: libcal-assets-nginx
    ports:
      - "8080:8080"
    depends_on:
      - watch
    environment:
      # LOCAL_SERVER: 42184b3c.ngrok.io
      LOCAL_SERVER: localhost:8080
    <<: *default-volumes
    